export { default as Navbar } from './common/Navbar.jsx';
export { default as Footer } from './common/Footer.jsx';
export { default as ScheduleDemoBtn } from './common/ScheduleDemoBtn.jsx';
export { default as Hero } from './Home/Hero';
export { default as EmailForm } from './common/EmailForm';
export { default as Features } from './Home/Features.jsx';
export { default as OtherFeatures } from './Home/OtherFeatures.jsx';
export { default as Brands } from './Home/Brands.jsx';
export { default as SimpleUI } from './Home/SimpleUI.jsx';
export { default as EasyToImplement } from './Home/EasyToImplement.jsx';
export { default as Heading } from './common/Heading';
export { default as Business } from './About/Business';
export { default as Culture } from './About/Culture';
export { default as People } from './About/People';
export { default as Vision } from './About/Vision';
export { default as Stats } from './About/Stats';
export { default as ReadyToStart } from './common/ReadyToStart';
export { default as Plans } from './Pricinng/Plans';
export { default as Form } from './Contact/Form';
export { default as FormAndBrands } from './Contact/FormAndBrands';
export { default as Companies } from './common/Companies'
export {default as ScrollToTop} from './common/ScrollToTop'
